DATA: L_COND TYPE STRING.
CONCATENATE ` mandt = '` SY-MANDT `'` INTO L_COND.

IF P_CLASS = 'ALL'.
  SORT GT_ZSTUDENT BY ID DESCENDING.
ENDIF.

IF P_CLASS IS NOT INITIAL.
  CONCATENATE L_COND ` and CLASS like '%` P_CLASS `%'` INTO L_COND.
ENDIF.

SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_ZSTUDENT
  FROM ZSTUDENT
 WHERE (L_COND) "mandt = 'sy-mandt' and ID like '%p_id%'
  ORDER BY ID.
