*&---------------------------------------------------------------------*
*& Include          ZR17_0020CLS
*&---------------------------------------------------------------------*
CLASS LCL_EVENT_RECEIVER DEFINITION.
    PUBLIC SECTION.
      METHODS : HANDLE_DATA_CHANGED
                    FOR EVENT DATA_CHANGED OF CL_GUI_ALV_GRID
        IMPORTING ER_DATA_CHANGED.
  
      METHODS : HANDLE_DOUBLE_CLICK
                    FOR EVENT DOUBLE_CLICK OF CL_GUI_ALV_GRID
        IMPORTING E_ROW
                    E_COLUMN
                    ES_ROW_NO.
  
      METHODS: HANDLE_TOOLBAR
                    FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
        IMPORTING E_OBJECT.
  
      METHODS : HANDLE_USER_COMMAND
                    FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
        IMPORTING E_UCOMM.
  
ENDCLASS.
  


CLASS LCL_EVENT_RECEIVER IMPLEMENTATION.
    METHOD : HANDLE_DATA_CHANGED.
      PERFORM HANDLE_DATA_CHANGED USING ER_DATA_CHANGED.
    ENDMETHOD.
  
    METHOD : HANDLE_DOUBLE_CLICK.  
    ENDMETHOD.
  
    METHOD : HANDLE_TOOLBAR.  
      PERFORM HANDLE_TOOLBAR USING E_OBJECT. 
    ENDMETHOD.
  
    METHOD : HANDLE_USER_COMMAND.
      PERFORM HANDLE_USER_COMMAND USING E_UCOMM. 
    ENDMETHOD.

ENDCLASS.
  
DATA : GO_EVENT_RECEIVER TYPE REF TO LCL_EVENT_RECEIVER.